### ISSUE TITLE
Cannot get detail on unowned item

### ISSUE THREAD

**Issue by bricecarpentier** [pozirk/AndroidInAppPurchase#10]
Hi,

I'm doing the following to fetch the skus of an unowned item :

``` actionscript3
var instance:InAppPurchase; // this is pseudo code obviously

instance.addEventListener(InAppPurchaseEvent.RESTORE_SUCCESS, onRestoreSuccess);
instance.restore([MY_ITEM_ID]); // needless to say I've checked that the ID indeed exists

function onRestoreSuccess(event:InAppPurchaseEvent):void
{
  var detail:InAppSkuDetails = instance.getSkuDetails(MY_ITEM_ID);
  // detail is null
}
```

I've managed to track down the issue to this commit : ebbed6feeab6fcfa6ec8dff54cfc85386f38e608

You added the following code to IABHelper.java

``` java
if (mSubscriptionsSupported) {
    r = queryPurchases(inv, ITEM_TYPE_SUBS);
    f (r != BILLING_RESPONSE_RESULT_OK) {
        throw new IabException(r, "Error refreshing inventory (querying owned subscriptions).");
    }

    if (querySkuDetails) {
        r = querySkuDetails(ITEM_TYPE_SUBS, inv, moreItemSkus);
        if (r != BILLING_RESPONSE_RESULT_OK) {
            throw new IabException(r, "Error refreshing inventory (querying prices of subscriptions).");
        }
    }
}
```

The side effect is that whenever one tries to call restore([MY_ID_1, MY_ID_2);, the IABHelper ends up filling the Inventory with the requested SKUs and **THEN** tries to fill it with the subscriptions. In my case there are none and I get an empty inventory. I'm unsure how to fix this. I deactivated subscriptions on my instance by changing <code> if(mSubscriptionsSupported)</code> to <code>if (false)</code>, but I guess something better should be done.

**Comment by joefaron** [comment]
lol
