### ISSUE TITLE
Error : Authentication required.

### ISSUE THREAD

**Issue by subramanya1989** [pozirk/AndroidInAppPurchase#28]
Hi ,

I have a problem. I uploaded the apk to alpha version of the Developer Console with mail id : abc@gmail.com and added Licence Tester account xyz@gmail.com and also Tester Group in alpha testors. And downloaded the apk after publishing directly from the app store. But still it gives error. I have only one Tester Account in my Tablet that too after Factory Data Reset. Still it gives error like -  Authentication required. You need to sign into your google account Please tell me what is the problem and solve it soon. 

Thanks...

**Comment by ArmanBM** [comment]
I Have Exactly the same Problem :(

**Comment by ArmanBM** [comment]
I Found the solution. you cant test inAppPurchase Completely before Publishing your app in alpha or beta test.
The only way to test IAP before these publish is to set product ID something like this: "android.test.purchased"
for more information check:
http://developer.android.com/google/play/billing/billing_testing.html
